### PR TITLE
(#72) Update cactoos to 0.39

### PR DESCRIPTION
**Pull request by victornoel**
#72 Update cactoos to 0.39

### CODE REVIEW

**Comment by victornoel** [comment]
@fabriciofx ping

**Comment by victornoel** [comment]
@llorllale REV seems not to be around here anymore... anyway to get a review for this? It is blocking other PRs.

**Comment by llorllale** [comment]
@0crat refuse

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/73#issuecomment-465373374))

@llorllale The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#73](https://github.com/yegor256/cactoos-http/issues/73), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
This pull request [#73](https://github.com/yegor256/cactoos-http/issues/73) is assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/c7187be3-371a-4e54-8d4e-c322a01e2419); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31):

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#73](https://github.com/yegor256/cactoos-http/issues/73) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Pull request merged**
