### PR TITLE
#5 The implementation here is not effective.

### PR DESCRIPTION
**Pull request by VsSekorin**
As per #5

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#12](https://github.com/yegor256/cactoos-http/issues/12) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#12](https://github.com/yegor256/cactoos-http/issues/12) is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/941388317); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by yegor256** [comment]
@0crat refuse

**Comment by VsSekorin** [comment]
@yegor256 Agreed. Read byte by byte is not most effective way. As discussed at StackOverflow, `BufferedReader` is best way to read first line from `InputStream`.

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
This pull request [#12](https://github.com/yegor256/cactoos-http/issues/12) is assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1101533369); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by SharplEr** [comment]
@rultor good to merge
@VsSekorin Nice PR)

**Comment by llorllale** [comment]
@rultor merge

**Comment by llorllale** [comment]
@yegor256 hold off on the merge!

**Comment by llorllale** [comment]
@VsSekorin please remove the puzzle

**Comment by VsSekorin** [comment]
@llorllale removed

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#12](https://github.com/yegor256/cactoos-http/issues/12) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@SharplEr According to our Policy:
> The code reviewer found at least three problems in the code;

There were no issues found from your side during this review. Please confirm that you'll try to find at least three problems in future reviews.

**Comment by SharplEr** [comment]
@elenavolokhova confirm

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
