### PR TITLE
(#82) updating maven-compiler-plugin version to fix the bug that does…

### PR DESCRIPTION
**Pull request by ocristian**
This is for #82.

As requested in the issue, plugin updated and set useIncrementalCompilation configuration.

### CODE REVIEW

**Comment by 0crat** [comment]
@ocristian[/z](https://www.0crat.com/u/ocristian) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please review this and merge or reject

**Comment by paulodamaso** [comment]
@ocristian Thank you!

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos-http#97` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
