### PR TITLE
(#99) Using org.cactoos.scalar.Binary instead of procedural code

### PR DESCRIPTION
**Pull request by iakunin**
This is for https://github.com/yegor256/cactoos-http/issues/99

There are so many files affected because I've updated `cactoos` as it was mentioned in todo.

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#100](https://github.com/yegor256/cactoos-http/issues/100) is now in scope, role is `REV`

**Comment by iakunin** [comment]
@paulodamaso seems that there is no assignee to review this PR

**Comment by paulodamaso** [comment]
@0crat  status

**Comment by iakunin** [comment]
@fabriciofx @paulodamaso could you review this PR, please?

**Comment by iakunin** [comment]
@paulodamaso can you refuse it for @fabriciofx so that someone else is assigned?

**Comment by paulodamaso** [comment]
@iakunin @0crat should make it. lf I unassign him, he won't be penalized by the delay, so let's see why @0crat isn't unassigning people

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos-http/issues/100#issuecomment-551898381); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
@iakunin Filed an issue in https://github.com/zerocracy/farm/issues/2196

**Comment by iakunin** [comment]
@paulodamaso great! Thank you

**Comment by paulodamaso** [comment]
@fabriciofx @iakunin Thanks people

**Comment by paulodamaso** [comment]
@rultor merge

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Code review was too long (17 days), architects (@paulodamaso) were penalized, see [§55](http://www.zerocracy.com/policy.html#55)

**Comment by 0crat** [comment]
The job [#100](https://github.com/yegor256/cactoos-http/issues/100) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by sereshqua** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by iakunin** [comment]
@sereshqua could you explain why the quality is bad? I as a developer tried my best to get this task done, but eventually I got no reward. Why’s that?

**Comment by sereshqua** [comment]
@iakunin it is not related to you, it is the code reviewer who has just accepted PR without finding any issue

**Comment by iakunin** [comment]
@sereshqua thank you for the explanation

**Pull request merged**
