### PR TITLE
#4 HtHead

### PR DESCRIPTION
**Pull request by VsSekorin**
As per #4

### CODE REVIEW

**Comment by 0crat** [comment]
Job [#24](https://github.com/yegor256/cactoos-http/issues/24) is now in scope, role is `REV`

**Comment by 0crat** [comment]
This pull request [#24](https://github.com/yegor256/cactoos-http/issues/24) is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/951954654); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @yegor256[/z](https://www.0crat.com/u/yegor256) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#24](https://github.com/yegor256/cactoos-http/issues/24), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -15 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
This pull request [#24](https://github.com/yegor256/cactoos-http/issues/24) is assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1101539683); the budget is 15 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§27](http://www.zerocracy.com/policy.html#27) and when you decide to accept the changes, inform @llorllale[/z](https://www.0crat.com/u/llorllale) (the architect) right in this ticket; if you decide that this PR should not be accepted ever, also inform the architect; this [blog post](http://www.yegor256.com/2015/02/09/serious-code-reviewer.html) will help you understand what is expected from a code reviewer

**Comment by SharplEr** [comment]
@VsSekorin  First of all I can't accept PR which doesn't pass checks. Please add tests to your PR.

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment]
@VsSekorin This issue from `pdd`, so you have to remove a corresponding puzzle. And please fix the problem with code coverage.

**Comment by VsSekorin** [comment]
@SharplEr Now I can not create a test for a long text. #36  Maybe `wait #36`?

**Comment by SharplEr** [comment]
@VsSekorin wait for what? There are two options:
1. You add tests.
2. I say ` should not be accepted ever` to `ARC`

**Comment by VsSekorin** [comment]
@SharplEr fixed

**Comment by SharplEr** [comment]
@VsSekorin Why you can't generate test resource at random?

**Comment by VsSekorin** [comment]
@SharplEr How is that better?

**Comment by SharplEr** [comment]
@VsSekorin nevermind
@llorllale good to merge

**Comment by llorllale** [comment]
@VsSekorin I agree about test coverage: please add a puzzle to finish covering all branches [missed](https://codecov.io/gh/yegor256/cactoos-http/pull/24/diff?src=pr&el=tree#diff-c3JjL21haW4vamF2YS9vcmcvY2FjdG9vcy9odHRwL0h0U3RhdHVzLmphdmE=) for this implementation. A refactor may be due as well.

**Comment by VsSekorin** [comment]
@llorllale Added.
@SharplEr Thanks for idea.

**Comment by llorllale** [comment]
@rultor merge

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#24](https://github.com/yegor256/cactoos-http/issues/24) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by elenavolokhova** [comment]
@SharplEr According to our Policy:
> The code reviewer found at least three problems in the code 

As far as I can see only two issues were found during review.
Please, confirm that you'll try to find at least three issues next time.

**Comment by elenavolokhova** [comment]
@VsSekorin According to our Policy:
> All commit messages have links to issues

Please, follow this rule in your future tickets.

**Comment by VsSekorin** [comment]
@elenavolokhova I will. Thank you.

**Comment by elenavolokhova** [comment]
@VsSekorin Thanks!

**Comment by SharplEr** [comment]
@elenavolokhova confirm

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +15 point(s) just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Pull request merged**
